[package]
name        = "abscissa"
description = """
              Application microframework with support for command-line option parsing,
              configuration, error handling, logging, and shell interactions
              """
version     = "0.0.6" # Also update html_root_url in lib.rs when bumping this
license     = "Apache-2.0"
authors     = ["Tony Arcieri <tony@iqlusion.io>"]
edition     = "2018"
homepage    = "https://github.com/iqlusioninc/abscissa/"
repository  = "https://github.com/iqlusioninc/abscissa/tree/master/"
readme      = "README.md"
categories  = ["command-line-interface", "rust-patterns", "web-programming"]
keywords    = ["application", "container", "microservices", "framework", "service"]

[dependencies]
abscissa_derive = { version = "0", path = "abscissa_derive" }
canonical-path = "0.1"
chrono = { version = "0.4", optional = true, features = ["serde"] }
failure = "0.1"
failure_derive = "0.1"
gumdrop = { version = "0.5", optional = true }
isatty = { version = "0.1", optional = true }
lazy_static = "1"
log = { version = "0.4", optional = true }
semver = { version = "0.9", optional = true }
serde = { version = "1.0", optional = true }
simplelog = { version = "0.5", optional = true }
term = { version = "0.5", optional = true }
toml = { version = "0.4", optional = true }
zeroize = "0.6"

[dev-dependencies]
serde_derive = "1.0"

[features]
default = ["application", "chrono"]
application = [
    "config",
    "errors",
    "logging",
    "options",
    "semver",
    "status"
]
config = [
    "secrets",
    "serde",
    "status",
    "toml"
]
errors = []
logging = [
    "errors",
    "log",
    "simplelog"
]
options = [
    "errors",
    "gumdrop"
]
secrets = []
shell = [
    "errors",
    "isatty",
    "term",
]
status = ["shell"]

[badges]
travis-ci = { repository = "iqlusioninc/abscissa" }

[workspace]
members = [".", "abscissa_derive"]
