[package]
name        = "abscissa_derive"
description = "Custom derive support for the abscissa application microframework"
version     = "0.3.0-rc.0" # Also update html_root_url in lib.rs when bumping this
license     = "Apache-2.0"
authors     = ["Tony Arcieri <tony@iqlusion.io>"]
edition     = "2018"
homepage    = "https://github.com/iqlusioninc/abscissa"
repository  = "https://github.com/iqlusioninc/abscissa/tree/develop/abscissa_derive"
readme      = "README.md"

[badges]
travis-ci = { repository = "iqlusioninc/abscissa", branch = "develop" }
maintenance = { status = "actively-developed" }

[lib]
proc-macro = true

[dependencies]
darling = "0.9"
heck = "0.3"
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.15"
synstructure = "0.10"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--document-private-items"] # Document all modules
