[package]
name        = "abscissa"
description = """
              Application microframework with support for command-line option parsing,
              configuration, error handling, logging, and terminal interactions.
              This crate contains a CLI utility for generating new applications.
              """
version     = "0.2.1" # Also update html_root_url in lib.rs when bumping this
license     = "Apache-2.0"
authors     = ["Tony Arcieri <tony@iqlusion.io>"]
edition     = "2018"
homepage    = "https://github.com/iqlusioninc/abscissa/"
repository  = "https://github.com/iqlusioninc/abscissa/tree/develop/"
readme      = "../README.md"
categories  = ["command-line-interface", "rust-patterns"]
keywords    = ["abscissa", "cli", "application", "framework", "service"]

[badges]
travis-ci = { repository = "iqlusioninc/abscissa", branch = "develop" }

[dependencies]
failure = "0.1"
gumdrop = "0.6"
handlebars = "2"
heck = "0.3"
lazy_static = "1"
serde = { version = "1", features = ["serde_derive"] }

[dependencies.abscissa_core]
version = "0.2"
path = "../core"

[dev-dependencies.abscissa_core]
version = "0.2"
features = ["testing"]
path = "../core"
